steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/summer-presence-388904/python-repo/my-app:v1', '.' ]
    #args: [
     #       'build', '-t', 'us-central1-docker.pkg.dev/My First Project/python-repo/my-app:${SHORT_SHA}', '.'
     #     ]
 # comment
  # Docker push to Google Artifact Registry
  #- name: 'gcr.io/cloud-builders/docker'
   # args: ['push',  'us-central1-docker.pkg.dev/My First Project/python-repo/my-app:${SHORT_SHA}']

#options:
 # logging: CLOUD_LOGGING_ONLY
  
# Store images in Google Artifact Registry 
#images:
 # - us-central1-docker.pkg.dev/My First Project/python-repo/my-app:${SHORT_SHA}
  
