steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/gcp-1340501-cr-prod/python-repo/my-app:v1', '.' ]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/gcp-1340501-cr-prod/python-repo/my-app:v1']

#images: ['us-central1-docker.pkg.dev/summer-presence-388904/python-repo/my-app:v1'] 

#options:
#  logging: GCS_ONLY
options:
  logging: CLOUD_LOGGING_ONLY
  
# Store images in Google Artifact Registry  

  
